export const URSER_LOGIN_LOADING = "URSER_LOGIN_LOADING";
export const URSER_LOGIN_SUCCESS = "URSER_LOGIN_SUCCESS";
export const URSER_LOGIN_FAILURE = "URSER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";
