export const GET_ALL_STUDENTS_LOADING = "GET_ALL_STUDENTS_LOADING";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";
export const GET_ALL_STUDENTS_FAILURE = "GET_ALL_STUDENTS_FAILURE";

export const GET_SINGLE_STUDENT_LOADING = "GET_SINGLE_STUDENT_LOADING";
export const GET_SINGLE_STUDENT_SUCCESS = "GET_SINGLE_STUDENT_SUCCESS";
export const GET_SINGLE_STUDENT_FAILURE = "GET_SINGLE_STUDENT_FAILURE";

export const GET_TESTS_LOADING = "GET_TESTS_LOADING";
export const GET_TESTS_SUCCESS = "GET_TESTS_SUCCESS";
export const GET_TESTS_FAILURE = "GET_TESTS_FAILURE";

export const ADD_NEW_TEST_LOADING = "ADD_NEW_TEST_LOADING";
export const ADD_NEW_TEST_SUCCESS = "ADD_NEW_TEST_SUCCESS";
export const ADD_NEW_TEST_FAILURE = "ADD_NEW_TEST_FAILURE";

export const EDIT_ONE_TEST_LOADING = "EDIT_ONE_TEST_LOADING";
export const EDIT_ONE_TEST_SUCCESS = "EDIT_ONE_TEST_SUCCESS";
export const EDIT_ONE_TEST_FAILURE = "EDIT_ONE_TEST_FAILURE";

export const DELETE_ONE_TEST_LOADING = "DELETE_ONE_TEST_LOADING";
export const DELETE_ONE_TEST_SUCCESS = "DELETE_ONE_TEST_SUCCESS";
export const DELETE_ONE_TEST_FAILURE = "DELETE_ONE_TEST_FAILURE";
